theme: jekyll-theme-minimal
title: Pano3D
show_downloads: true
description: A 360 depth estimation benchmark

github:
    form_url: https://forms.gle/uCAZutW8PGzR8Mhn9
    zenodo_url: https://vcl3d.github.io/Pano3D/download/#Download
    repository_url: https://github.com/VCL3D/Pano3D
    is_project_page: true
    repository_name: Pano3D
    owner_url: https://github.com/tzole1155
    owner_name: Giorgos Albanis

google_analytics: UA-176089043-1
