theme: jekyll-theme-minimal
title: UAVA 
show_downloads: true
description: A dataset for UAV assistant tasks

github:
    form_url: https://forms.gle/uCAZutW8PGzR8Mhn9
    zenodo_url: https://zenodo.org/record/3994337#.X0PCeegzaUk
    repository_url: https://github.com/VCL3D/UAVA
    is_project_page: true
    repository_name: UAVA
    owner_url: https://github.com/tzole1155
    owner_name: Giorgos Albanis


google_analytics: UA-176089043-1
